### ISSUE TITLE
Fatal error: Uncaught BattleEngine\Error:

### ISSUE THREAD

**Issue by ozandem** [patrykstefanski/og-battle-engine#1]
Hi, i would like the try your code but when i run example.php it returns with this;

`Fatal error: Uncaught BattleEngine\Error: '.' is not recognized as an internal or external command, operable program or batch file. in C:\xampp\htdocs\deneme\BattleEngine.php:452 Stack trace: #0 C:\xampp\htdocs\deneme\example.php(98): BattleEngine\BattleEngine->battle(Array, Array) #1 {main} thrown in C:\xampp\htdocs\deneme\BattleEngine.php on line 452`

**Comment by patrykstefanski** [comment]
Hi,

This happens when the battle engine path specified in _example.php_ is incorrect.

You can download the executable in [releases](https://github.com/patrykstefanski/og-battle-engine/releases) page. I am assuming you are using Windows, so please download _BattleEngine-win.exe_ file.

After that, modify this [line](https://github.com/patrykstefanski/og-battle-engine/blob/master/example.php#L97) in _example.php_ with your path:
```php
$battleEngine = new BattleEngine('./build/BattleEngine', OG::$unitsAttributes);
```

For instance, if you download it to _Downloads_ folder, it should look more or less like that:
```php
$battleEngine = new BattleEngine('C:\Users\YOUR-USERNAME\Downloads\BattleEngine-win.exe', OG::$unitsAttributes);
```

**Comment by ozandem** [comment]
Thank you, it works now. Great job!
